spring:
  application:
    name: Welcome-API1
  boot:
    admin:
      client:
        url:
          - http://localhost:1111/

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

server:
  port: 9092
