server:
  port: 9091
spring:
  application:
    name: WelcomeAPI
  boot:
    admin:
      client:
        url: http://localhost:1111/
  cloud:
    compatibility-verifier:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
